# Use root/mysql as user/password credentials

version: '3.8'

services:
  python_apis:
    build:
      context: ./
      dockerfile: Dockerfile
    image: prueba-web
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    hostname: web

  bases_de_datos:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bw1L[{wezRx9
      MYSQL_DATABASE: webtofly_asegurarse
      MYSQL_USER: webtofly_db_user
      MYSQL_PASSWORD: bw1L[{wezRx9
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    hostname: adminer

# volumes:
#   db_volume:
#   pgadmin-data:
